#ifndef UTIL_ERROR_H
#define UTIL_ERROR_H

enum core_error {
    CORE_SUCCESS,
    CORE_FAILURE,
    CORE_INVALID_NULLPTR,
    CORE_OUT_OF_MEMORY,
    CORE_CANNOT_ALLOC_MEMORY,
    CORE_INVALID_VAR
};

#endif /* UTIL_ERROR_H */
