#ifndef UTIL_ERROR_H
#define UTIL_ERROR_H

enum core_error {
    CORE_ERROR_SUCCESS,
    CORE_ERROR_FAILURE,
    CORE_ERROR_INVALID_NULLPTR,
    CORE_ERROR_CANNOT_ALLOC_MEMORY,
    CORE_ERROR_INVALID_VAR
};

#endif /* UTIL_ERROR_H */
