#ifndef UTIL_ERROR_H
#define UTIL_ERROR_H

typedef enum {
    CORE_SUCCESS = 0,
    CORE_FAILURE,
    CORE_NULLPTR,
    CORE_OUT_OF_MEMORY,
    CORE_ACCESS_DENIED,
    CORE_INVALID_ARG,
    CORE_FILE_NOT_FOUND,
    CORE_FILE_CORRUPT,
    CORE_GLFW,
    CORE_GL,
} core_error;

#endif // UTIL_ERROR_H
